### ISSUE TITLE
01/15/2019

### ISSUE THREAD

**Issue by ziyixi** [ziyixi/Daily_research#1]
#### TODO
- [x] Run a Meshfem for using precise grid
  + [x] Find the difference between regional crust and the global one
- [x] Reorganize the file structure putting three different mesh files
- [x] Build a pipeline to combine two bin files
- [x] Test the code to read in the bin file
- [ ] Select two events in Tao Kai's Paper
- [x] Compare the result of different cases

**Comment by ziyixi** [comment]
#### Problems now we have:
+ there is some error in tao's mesh, Prof. Chen says it may relate to the abrupt change of mantle velocity value. 
+ I should find cases in different condition of Tao Kai's code.
