### ISSUE TITLE
01/17/2019

### ISSUE THREAD

**Issue by ziyixi** [ziyixi/Daily_research#2]
#### TODO

- [ ] find each condition described in the Tao's code and give an example of the cases.
- [x] develop a method to draw figures related to the outputed VTK files or directly from the bin files.
    + learn how Paraview could make slices, contour and find specific data, need to develop a way to convert different coordinate system. 
    + need to modify combine_vol_data.F90, set CORRECT_ELLIPTICITY as true, so that we can remove the ellipticity factor. (This should be a better way comparing with modify the Parfile)    
- [ ] find the point where there is a bug saying having the negative velocity value.
- [ ] find what will happen if using different style of mesh.
- [ ] find where my simulation region there is a a deep moho.
- [ ] find a better criterion to combine different models.
- [ ] find a good way to smooth the model, center-> outside give different weight.
