### ISSUE TITLE
01/23/2019

### ISSUE THREAD

**Issue by ziyixi** [ziyixi/Daily_research#3]
#### TODO
- [x] Debug for the memory lease of the plotting function.
- [ ] Using Jupyter widget to show the figures.
- [x] Run the debug function to find the reason why there are negative points.
- [ ] Handle issues related to the Moho that goes through the element.
- [ ] Find a way to display the interpolation result into Paraview.

**Comment by ziyixi** [comment]
#### Handle issues related to the Moho that goes through the element.
+ in each element, the interpolation of 125 gll points doesn't change the status of ele_in_crust/mantle. (crust smoothing)
+ it seems the moho cut through the element. So I should find way to change this manner. May relate to the way to define the moho depth.
+ An idea:
>  - find in which element the Moho goes through it.
>  - Replace all the physical properties above the Moho the value just slightly bellow the Moho in this element. (may have to consider how the Moho go through it) 
>  - Do interpolation.
>  - Put the Crust 1.0 on it.
+ The above method will not modify TaoKai's code, and now I should look into the problem related to the ellipticity.
+ Handle the problem of ellipticity is kind of complex, also we could create a reference model without ellipticity, then use the model got to decide whether this GLL point is above the Moho or not.
+ Although by modifying compute_element_properties.f90, we could print the elem_in_crust and elem_in_mantle, but actually we could directly print, for the old bin, which GLL point is in which region: anyway for this GLL point, we have the Moho and r. (should be the best method)

**Comment by ziyixi** [comment]
#### Debug for the memory lease of the plotting function.
+ may have problem by creating too many fig objects, may pass fig as a parameter. (wrong)
+ test fig.close() (wrong, no warning, but still be killed)
+ Find the reason why selecting remaining figures has the bug, and downloaded all the figures using this method.

**Comment by ziyixi** [comment]
#### Run the debug function to find the reason why there are negative points.
+ It seems in the old element where the bug appears, it's the element have the moho cutting throgh. So finding a way to consider this problem is important. 
+ The problem is in the shallowest layers, the first case should be tested later. But there are problems why in the shallowest layers, it's not continuous from an overview.
+ The problem could be solved lay the crust 1.0 after reading in the bin file.

**Comment by ziyixi** [comment]
#### Progress:
+ Having changed the code in Specfem, waiting to run to see the result.
