### ISSUE TITLE
01/29/2019

### ISSUE THREAD

**Issue by ziyixi** [ziyixi/Daily_research#5]
#### TODO

+ [ ] Complete the modification of TaoKai's code.
+ [ ] Test different smoothing options, find the reason why there is a gap in the curst model.
+ [ ] test how many elements that has the similar problem.
+ [ ] develop a way to directly use the perturbation.
+ [ ] find a way to determine the distance between a certain point with the big circle, using this method as the constrain for smoothing.
+ [ ] test the result between smoothing and not.

**Comment by ziyixi** [comment]
#### find a way to determine the distance between a certain point with the big circle, using this method as the constrain for smoothing.

+ I should look at the Specfem's code to see its rotation. (have found the part where do the rotation, develop using [CoordinateTransformations.jl](https://github.com/FugroRoames/CoordinateTransformations.jl)) But I have to find way to rotate back.

+ It seems the above method is not so easy, We could use two parts division method to find the nearest point, we should look at [Great-circle navigation](https://en.wikipedia.org/wiki/Great-circle_navigation)

+ I could also use https://github.com/anowacki/Geodesics.jl to uniformly get test points.
