### ISSUE TITLE
02/01/2019

### ISSUE THREAD

**Issue by ziyixi** [ziyixi/Daily_research#6]
#### TODO:

+ [x] debug for my adaption of Tao Kai's code.
+ [x] find the exact reason in Specfem about the formation of the abnormal value and try to smooth it.
+ [ ] calculate the input model without smoothing.
+ [ ] find the mathematical expression of the smoothing region.
+ [ ] write down the code of the smoothing.
+ [ ] get the sync result for different cases and compare with the data.

**Comment by ziyixi** [comment]
#### debug for my adaption of Tao Kai's code.

+ [x] find the accurate igll and iproc of the abnormal point. igll could be calculated using `igll = igllx + NGLLX * ( (iglly - 1) + NGLLY * ( (igllz - 1) + NGLLZ * ( (ispec - 1))))`.
+ [x] when we are at this igll, print `location_1slice`, `model_gll_old` and `model_interp`.
+ [x] print the same information at this point for tao's code.
+ [x] compare where is the difference and analysis the possible reason.

#### Result 
+ CartesianIndex(5, 2, 4, 3943, 387),492835
+ I find the reason why there is an abnormal value is that my code takes s362ani's value while tao didn't. But then how to explain the difference between tao's result and s362ani, just a little perturbation?
+ `/work/05880/tg851791/stampede2/specfem/20190115/simulation_taoreg/DATABASES_MPI` false
+ `/work/05880/tg851791/stampede2/model/model_interp/debug/tapreg_adds363ani_addtaosmooth` true
+ put the old_bin and new_bin the same, an interesting result
+ why 125 lagrange(ignore)
+ the reason of bug is fld(num,3)

**Comment by ziyixi** [comment]
#### find the exact reason in Specfem about the formation of the abnormal value and try to smooth it.

+ [x] read the coding part of smoothing crust1.0
+ [x] guess the reason why it happens.

#### Result
+ there is no good to turn the flag SMOOTH_CRUST_EVEN_MORE true, as it will have a jump of smoothing.
+ find the reason, smoothing the third sediment layer with value equal to 0.

**Comment by ziyixi** [comment]
#### calculate the input model without smoothing

+ [x] write up the code to generate perturbation.
+ [x] use the perturbation to get the corresponding stacking bin files (workflow)
+ [ ] generate the perturbation. (run scripts)

#### problems
+ It seems /work/05880/tg851791/stampede2/model/FWEA18_smooth has some abnormal values. maybe changed the initial value? write and read? find a way to avoid that.
